# Generated by Django 4.2.17 on 2025-02-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "receiver_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("encrypted_image", models.TextField()),
                (
                    "decrypted_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="decrypted_images/"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
