# Generated by Django 5.1.4 on 2025-02-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_imagehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageHistory",
        ),
    ]
