# Generated by Django 4.2.7 on 2025-03-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_encryptedimage_delete_imagehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptedImage",
        ),
    ]
